/**
 * This code was generated by Builder.io.
 */
"use client";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import React from "react";

import Footer from "@/components/Footer";
import Slide from "./slide";
import ContentSection from "./ContenSec";
import EventPromoSection from "./EventPromo";
import Artikel from "./Artikel";
import ProductSlide from "./ProductSlide";
import Product from "./Product";
import Carousel from "./Carousel";
import "../globals.css";
import Navbar from "@/components/Navbar";

const LandingPage = () => {
  const slides = [
    { image: "slide1.png", alt: "Product 1" },
    { image: "bghome.png", alt: "Product 2" },
    { image: "slide1.png", alt: "Product 3" },
  ];

  return (
    <div className="flex flex-col">
      <div className="flex overflow-hidden flex-col w-full max-md:max-w-full">
        <Navbar/>
        <main className="">
          <Carousel slides={slides} />
          <ContentSection />
          <Artikel />
          <EventPromoSection />
          <Product />
          <ProductSlide />
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default LandingPage;
